### ISSUE TITLE
"ERROR: No Chromosome and Position fields in input text" and other errors

### ISSUE THREAD

**Issue by hannah-happ** [CAG-CNV/MONTAGE#2]
Hello! I have been trying to get MONTAGE to work but am finding it won't run with the provided test files. I have installed the software, unzipped the .int.csv file, but when I run 

`$ perl Montage.pl 6184541022_R02C02.int.csv > tmp.txt`

I get tons of errors. When I grep "ERROR" in the tmp file, I get the following: 
`$ grep "ERROR" tmp.txt
ERROR: No Chromosome and Position fields in input file . Please specify --signalposfile map.txt
ERROR: No Chromosome and Position fields in input file Name    Chr    Position    sample.BAF    sample.LRR. Please specify --signalposfile map.txtERROR: No Chromosome and Position fields in input file rs12354060    1    22886    1    -0.1233.
Please specify --signalposfile map.txtERROR: No Chromosome and Position fields in input file rs2691310    1    59693    0.385    -0.1224.
Please specify --signalposfile map.txtERROR: No Chromosome and Position fields in input file rs2531266    1    72277    0.5943    -0.05391.`

It seems like the supplied csv file is fine:
`$ head -n2 6184541022_R02C02.int.csv
Name    Chr    Position    sample.BAF    sample.LRR
rs12354060    1    22886    1    -0.1233`

Because of this, the program can't parse and variables go undefined, so I end up with syntax errors like the one in heweihuang's issue.

I have also had our high performance computing team try their hand at this in case it was an installation issue, but they are having the same issue. Any help would be greatly appreciated, as I'm eager to get this tool working! Thank you!

**Comment by joeglessner1** [comment]
Hi, I think I understand the point of confusion now. I intended the input file specified to be "list_BafLrr_SignalFiles.txt" which is a text file containing many different signal files (also known as .int.csv or baflrr files) possibly at different paths. This way for larger runs, the command line is not cluttered by many space delimited input files. However, I see your perspective now when we just want to test one input file, it is more intuitive to simply provide the file name directly rather than a file with that one file name contained in it. I just edited Montage.pl to check if the input file specified has more than one tab delimited column, indicating the input is directly specified vs. input specified within a list file. The output will be named \<FirstSignalFileName\>_Montage.cleancnv and \<FirstSignalFileName\>_Montage.log but will contain the output of all space delimited inputs specified on the command line rather than the input list file representing a multiple samples run. Let me know if still issues.
